# Generated by Django 6.0.4 on 2026-04-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final')], max_length=20)),
                ('technical_competence', models.IntegerField(default=1)),
                ('professionalism', models.IntegerField(default=1)),
                ('communication', models.IntegerField(default=1)),
                ('teamwork', models.IntegerField(default=1)),
                ('problem_solving', models.IntegerField(default=1)),
                ('overall_rating', models.FloatField(editable=False)),
                ('comments', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='placements.placement')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('tasks_completed', models.TextField()),
                ('skills_developed', models.TextField()),
                ('challenges', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor_seen', models.BooleanField(default=False)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='placements.placement')),
            ],
            options={
                'ordering': ['-week_number'],
                'unique_together': {('placement', 'week_number')},
            },
        ),
    ]
