# Generated by Django 6.0.4 on 2026-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='tasks_completed',
        ),
        migrations.AddField(
            model_name='progressreport',
            name='daily_logs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='supervisor_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='weekly_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='skills_developed',
            field=models.TextField(blank=True),
        ),
    ]
