# Generated by Django 6.0.4 on 2026-04-20 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_role', models.CharField(choices=[('student', 'Student'), ('organization', 'Organization'), ('supervisor', 'Supervisor')], max_length=20)),
                ('overall_rating', models.IntegerField(default=5)),
                ('would_recommend', models.BooleanField(default=True)),
                ('skills_gaps', models.JSONField(default=list)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='placements.placement')),
            ],
            options={
                'unique_together': {('placement', 'submitted_by_role')},
            },
        ),
    ]
